spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deepu
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: off
  application:
    name: PLANS-API
  boot:
    admin:
      client:
        url: http://localhost:9090/
management:
  endpoints:
    web:
      exposure:
        include: '*'
